apiVersion: v1
kind: Pod
metadata:
   # Name of Pod
  name: result-app-pod
  labels:
    # Name of Pod Label
    name: result-app-pod
    # Name of application running within the Pod
    app: demo-voting-app

spec:
  containers:
      # Container name
    - name: result-app
      image: dockersamples/examplevotingapp_result
      ports: 
          # Port container uses to connect to the Service
        - containerPort: 80