apiVersion: v1
kind: Pod
metadata:
   # Name of Pod
  name: worker-app-pod
  labels:
    # Name of Pod
    name: worker-app-pod
    # Name of Label running within the Pod
    app: demo-voting-app

spec:
  containers:
      # Container name
    - name: worker-app
      image: dockersamples/examplevotingapp_worker