apiVersion: v1
kind: Pod
metadata:
   # Name of Pod
  name: voting-app-pod
  labels:
    # Name of Pod Label
    name: voting-app-pod
    # Name of application running within the Pod
    app: demo-voting-app

spec:
  containers:
      # Container name
    - name: voting-app
      image: dockersamples/examplevotingapp_vote
      ports: 
          # Port container uses to connect to the Service
        - containerPort: 80